import type { Metadata } from 'next';

// import 'minireset.css';
import '@landing/styles/tailwind.css';
import '@landing/styles/global.css';
import Layout from './components/layout';
import { NavbarMobileMenuPortalProvider } from './contexts/navbar-mobile-menu-portal';
// import 'stylex-webpack/stylex.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <NavbarMobileMenuPortalProvider id="global-navbar-mobile-menu-portal">
          <Layout>
            {children}
          </Layout>
        </NavbarMobileMenuPortalProvider>
      </body>
    </html>
  );
}
